const express = require('express');
const { productController } = require('../Controller');
const router = express.Router();

router.get('/getAllProducts', productController.getAllProducts);
router.get('/getProduct', productController.getProduct);
router.get('/getProductId', productController.getProductId);
router.post('/AddProducts', productController.AddProducts);
router.delete('/DeleteProducts', productController.DeleteProducts);
router.patch('/EditProducts/:id', productController.EditProducts);
router.get('/getGroupByCategory', productController.getGroupByCategory);
router.get('/getProductCategory', productController.getProductCategory);
router.get('/getCategory', productController.getCategory);
router.post('/AddCategory', productController.addCategory);
router.patch('/EditCategory/:id', productController.editCategory);
router.delete('/DeleteCategory/:id', productController.deleteCategory);
router.get('/getSize', productController.getSize);
router.post('/AddSize', productController.addSize);
router.patch('/EditSize/:id', productController.editSize);
router.delete('/DeleteSize/:id', productController.deleteSize);
router.post('/AddPrice', productController.addPrice);
router.patch('/EditPrice/:id', productController.editPrice);
router.delete('/DeletePrice/:id', productController.deletePrice);
router.get('/getPrice', productController.getPrice);
router.get('/getStock', productController.getStock);
router.get('/getAllJumlahStock', productController.getAllJumlahStock);
router.get('/getStockId/:id', productController.getStockId);
router.delete('/DeleteStocks', productController.DeleteStocks);

module.exports = router;